//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsWPF.data.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        public int rent_id { get; set; }
        public int tenant_id { get; set; }
        public int shop_center_id { get; set; }
        public int employer_id { get; set; }
        public string num_pavilion { get; set; }
        public int status_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual employers employers { get; set; }
        public virtual pavilions pavilions { get; set; }
        public virtual statuses statuses { get; set; }
        public virtual tenants tenants { get; set; }
    }
}
