//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsWPF.data.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops_centers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shops_centers()
        {
            this.pavilions = new HashSet<pavilions>();
        }
    
        public int shop_center_id { get; set; }
        public string title { get; set; }
        public int status_id { get; set; }
        public int pavilions_count { get; set; }
        public string address { get; set; }
        public decimal cost { get; set; }
        public decimal value_added_factor { get; set; }
        public int floors_count { get; set; }
        public byte[] icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pavilions> pavilions { get; set; }
        public virtual statuses statuses { get; set; }
    }
}
